name: toqubo-benchmark

on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x64
    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.version }}
        arch: ${{ matrix.arch }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install ToQUBO.jl, PyQUBO, PyQUBO 0.4
      run: make install TOQUBO_BRANCH=px/refactor
    - name: Run benchmarks
      run: make run
    # - name: Profiling
    #   run: make perf
    - name: Make Plots
      run: make plot
    - name: Save Results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
      run: |
       git config --global user.name "GitHub Actions"
       git config --global user.email "suporte@psr-inc.com"
       git add -f ./benchmark/ToQUBO/tsp_ToQUBO.csv ./benchmark/pyqubo/tsp_pyqubo.csv ./benchmark/pyqubo_040/tsp_pyqubo_040.csv ./benchmark/qubovert/tsp_qubovert.csv ./benchmark/benchmark.png ./benchmark/toqubo.png
       git commit -m "Save Benchmark Results [actions]"
       git push
        

