name: toqubo-benchmark

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  benchmark:
    if: ${{ !(github.event_name == 'push') || contains(github.event.head_commit.message, '[run]') }}
    name: Julia ${{ matrix.julia-version }}, Python ${{ matrix.python-version }} @ ${{ matrix.os }}/${{ matrix.arch }}/${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - julia-version: '1.9'
            python-version: '3.11'
            os: ubuntu-latest
            arch: x64
    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
        arch: ${{ matrix.arch }}
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Benchmarks
      run: make run TOQUBO-BRANCH=master
    - name: Save Results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
      run: |
        git config --global user.name "PSR Actions"
        git config --global user.email "suporte@psr-inc.com"
        git add ./benchmark/**/results.*.csv
        git add ./data/report.json
        git commit -m "Save Benchmark Results [actions]"
        git push
