name: toqubo-benchmark

on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: ToQUBO.jl/PyQUBO Benchmarks
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.version }}
        arch: ${{ matrix.arch }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: make all

